METABOX_SRC_PATH="$(pwd)" \
METABOX_WORKING_DIR="~/__metabox_beta_working_dir" \
METABOX_DOCUMENT_FOLDERS="$(pwd)/documents/metabox_images_sp16" \
METABOX_LOG_LEVEL="INFO" \
METABOX_SP16_PRODUCT_KEY="NQGJR-63HC8-XCRQH-MYVCH-3J3QR" \
$1