SET "METABOX_SRC_PATH=%cd%"^
 && SET "METABOX_WORKING_DIR=%cd:~0,3%/__metabox_beta_working_dir"^
 && SET "METABOX_DOCUMENT_FOLDERS=%cd%/documents/metabox_images_sp16"^
 && SET "METABOX_LOG_LEVEL=INFO"^
 && SET "METABOX_SP16_PRODUCT_KEY=NQGJR-63HC8-XCRQH-MYVCH-3J3QR"
