METABOX_SRC_PATH="$(pwd)" \
METABOX_WORKING_DIR="~/__metabox_beta_working_dir" \
METABOX_DOCUMENT_FOLDERS="$(pwd)/documents" \
METABOX_LOG_LEVEL="INFO" \
METABOX_SP13_SP1_PRODUCT_KEY="NQTMW-K63MQ-39G6H-B2CH9-FRDWJ" \
METABOX_SP16_PRODUCT_KEY="NQGJR-63HC8-XCRQH-MYVCH-3J3QR" \
METABOX_JENKINS_UI_PORT="9081" \
METABOX_JENKINS_WEB_AGENT_PORT="33978" \
METABOX_CI_BOX_NAME="centos7-mb-jenkins2-beta" \
METABOX_JENKINS_INSTANCE_NAME="dev" \
$1