METABOX_SRC_PATH="$(pwd)" \
METABOX_WORKING_DIR="~/__metabox_beta_working_dir" \
METABOX_DOCUMENT_FOLDERS="$(pwd)/documents/metabox_images_sp13_sp1" \
METABOX_LOG_LEVEL="INFO" \
METABOX_SP13_SP1_PRODUCT_KEY="NQTMW-K63MQ-39G6H-B2CH9-FRDWJ" \
$1