SET "METABOX_SRC_PATH=%cd%"^
 && SET "METABOX_WORKING_DIR=%cd:~0,3%/__metabox_beta_working_dir"^
 && SET "METABOX_DOCUMENT_FOLDERS=%cd%/documents/metabox_images_sp13_sp1"^
 && SET "METABOX_LOG_LEVEL=INFO"^
 && SET "METABOX_SP13_SP1_PRODUCT_KEY=NQTMW-K63MQ-39G6H-B2CH9-FRDWJ"
